import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import Header from "@/components/Header";
import Navbar from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${inter.className} min-h-screen h-full transition-colors duration-300 container max-w-6xl mx-auto bg-[#f8f7ff] dark:bg-[#323232] text-[#323232] dark:text-[#f8f7ff] scroll-smooth`}
      >
        <Providers>
          <Header />
          <Navbar />
          <main className="max-w-5xl mx-auto  ">{children}</main>
        </Providers>
      </body>
    </html>
  );
}
